language: python

python:
  - '3.7'

cache: pip

branches:
  only:
    - master
    - dev

deploy:
  provider: pypi
  user: __token__
  password:
    secure: dvvHQhVVDxd1GKMr0PPYYVhGsNUlEK4scHOGkOc2AubQKpbTNmHJ35WhlQCrYiREo17zPvN/yCWvBw0sDdkWrKtOGNIRoEcRBsUqedkRzKD6zY/j0H+J1qQKKLR92pxXSBANueCCQkB7KuppI7RNUuzTK1/WvWqFIMEA2EuaZJP6HundyWReXTAI3V4syl1mQw+wPm+bCytBcd+3xa28ibTSlmwgG2JcDDOj4HGN7d7gqk3CbXfeqIPZ84FmyDH9DNeMhnUascwXeE6Kv0TXC7BSNDnW/3UTpVB7FFJxB7nUBOxcWAqp+jzjgVryh0CSYWHbNZevHXJNIsh4iop3z0vJOsFPi1P4bQ6acRLxppmSZLTtv6mn0p18jt6gDijhtWjK9Uve7q5QMyNcgd7yOpUDVxBbRxWng9YpA+9Sz6s+VH8I2UCtej1bqBNl/W/5f6h5KcMGWUcXAKzYkwbkGEQxbxPdrP8Sr7VrQPp4ca79AOdo/YmwYp3BoZnkehSZ1uTMCGbxqmfGPVgoPMXFq5o92pp6AfRH86K8MhVI2MZza/JI8zMkiuT3Hn459QjjvEHQolexipbPDYUlZRId86lO5kz7rw4/bfhmrwcDD4BUFi3dTn0G25dNVmOFm/WcnuKMmUCQz/gO/+dv2DkE2IWMCJaoB/xFauHksxXzjRM=
  skip_existing: true
  distributions: 'sdist bdist_wheel'
  on:
    tags: true

script:
  - pip install flake8
  - flake8
  - make test
  - make doc DOCS_FILEPATH=docs/api.md.tmp
  - cmp --silent docs/api.md docs/api.md.tmp
