language: python

python:
  - "3.7"

cache: pip

branches:
  only:
    - master
    - dev

script:
  - pip install flake8
  - flake8
  - python setup.py test
  - pydocmd simple substratools.Algo+ substratools.Metrics+ substratools.Opener+> docs/api.md.tmp
  - cmp --silent docs/api.md docs/api.md.tmp
